// Auto-generated by scripts/generate-services-from-openapi.mjs
// Do not edit this file manually.

import type {
  ActionCallOptions,
  ActionRequest,
  ActionResponsePayload,
} from "./types.js";
import type { FusionClient, FusionTaskResource } from "./client.js";

export type ActionInvoker<TKey extends string> = (
  request?: ActionRequest<TKey>,
  options?: ActionCallOptions,
) => Promise<ActionResponsePayload<TKey>>;

export interface FusionTaskShortcutProperties {
  readonly cphoneNanoBanana: FusionTaskResource<"cphone-nano-banana">;
  readonly doubaoStt: FusionTaskResource<"doubao-stt">;
  readonly doubaoTts: FusionTaskResource<"doubao-tts">;
  readonly falAuraSr: FusionTaskResource<"fal-aura-sr">;
  readonly falFluxProKontext: FusionTaskResource<"fal-flux-pro-kontext">;
  readonly falNanoBanana: FusionTaskResource<"fal-nano-banana">;
  readonly falNanoBanana2: FusionTaskResource<"fal-nano-banana-2">;
  readonly falNanoBananaPro: FusionTaskResource<"fal-nano-banana-pro">;
  readonly falRemoveBackground: FusionTaskResource<"fal-remove-background">;
  readonly falSora2ImageToVideo: FusionTaskResource<"fal-sora2-image-to-video">;
  readonly falSora2TextToVideo: FusionTaskResource<"fal-sora2-text-to-video">;
  readonly imageTranslate: FusionTaskResource<"image-translate">;
  readonly mangaZipTranslate: FusionTaskResource<"manga-zip-translate">;
  readonly oomolTts: FusionTaskResource<"oomol-tts">;
  readonly pdfTransformEpub: FusionTaskResource<"pdf-transform-epub">;
  readonly pdfTransformMarkdown: FusionTaskResource<"pdf-transform-markdown">;
  readonly qwenMtImage: FusionTaskResource<"qwen-mt-image">;
  readonly wanxImage: FusionTaskResource<"wanx-image">;
  readonly wanxKf2vVideo: FusionTaskResource<"wanx-kf2v-video">;
}

export interface FusionActionShortcutProperties {
  readonly customFinancialFundamentalReport: {
    readonly predefinedQuestions: ActionInvoker<"custom-financial-fundamental-report/predefined-questions">;
    readonly report: ActionInvoker<"custom-financial-fundamental-report/report">;
    readonly reportList: ActionInvoker<"custom-financial-fundamental-report/report-list">;
  };
  readonly doubaoTextToImageSeedream: {
    readonly generate: ActionInvoker<"doubao-text-to-image-seedream/generate">;
  };
  readonly fileUpload: {
    readonly abortMultipartUpload: ActionInvoker<"file-upload/abort-multipart-upload">;
    readonly completeMultipartUpload: ActionInvoker<"file-upload/complete-multipart-upload">;
    readonly createMultipartUpload: ActionInvoker<"file-upload/create-multipart-upload">;
    readonly generatePresignedUrl: ActionInvoker<"file-upload/generate-presigned-url">;
    readonly generatePresignedUrls: ActionInvoker<"file-upload/generate-presigned-urls">;
  };
  readonly jinaReader: {
    readonly read: ActionInvoker<"jina-reader/read">;
    readonly search: ActionInvoker<"jina-reader/search">;
  };
  readonly qwenDocTurbo: {
    readonly analyze: ActionInvoker<"qwen-doc-turbo/analyze">;
  };
  readonly qwenImageEditPlus: {
    readonly edit: ActionInvoker<"qwen-image-edit-plus/edit">;
  };
  readonly textToEpubIllustrate: {
    readonly generate: ActionInvoker<"text-to-epub-illustrate/generate">;
  };
  readonly tinifyPngShrink: {
    readonly compress: ActionInvoker<"tinify-png-shrink/compress">;
  };
}

function createActionInvoker<TKey extends string>(
  client: FusionClient,
  key: TKey,
): ActionInvoker<TKey> {
  return (request, options) => client.action(key, request, options);
}

export function createTaskShortcuts(
  client: FusionClient,
): FusionTaskShortcutProperties {
  return {
    cphoneNanoBanana: client.task("cphone-nano-banana"),
    doubaoStt: client.task("doubao-stt"),
    doubaoTts: client.task("doubao-tts"),
    falAuraSr: client.task("fal-aura-sr"),
    falFluxProKontext: client.task("fal-flux-pro-kontext"),
    falNanoBanana: client.task("fal-nano-banana"),
    falNanoBanana2: client.task("fal-nano-banana-2"),
    falNanoBananaPro: client.task("fal-nano-banana-pro"),
    falRemoveBackground: client.task("fal-remove-background"),
    falSora2ImageToVideo: client.task("fal-sora2-image-to-video"),
    falSora2TextToVideo: client.task("fal-sora2-text-to-video"),
    imageTranslate: client.task("image-translate"),
    mangaZipTranslate: client.task("manga-zip-translate"),
    oomolTts: client.task("oomol-tts"),
    pdfTransformEpub: client.task("pdf-transform-epub"),
    pdfTransformMarkdown: client.task("pdf-transform-markdown"),
    qwenMtImage: client.task("qwen-mt-image"),
    wanxImage: client.task("wanx-image"),
    wanxKf2vVideo: client.task("wanx-kf2v-video"),
  };
}

export function createActionShortcuts(
  client: FusionClient,
): FusionActionShortcutProperties {
  return {
    customFinancialFundamentalReport: {
      predefinedQuestions: createActionInvoker(client, "custom-financial-fundamental-report/predefined-questions"),
      report: createActionInvoker(client, "custom-financial-fundamental-report/report"),
      reportList: createActionInvoker(client, "custom-financial-fundamental-report/report-list"),
    },
    doubaoTextToImageSeedream: {
      generate: createActionInvoker(client, "doubao-text-to-image-seedream/generate"),
    },
    fileUpload: {
      abortMultipartUpload: createActionInvoker(client, "file-upload/abort-multipart-upload"),
      completeMultipartUpload: createActionInvoker(client, "file-upload/complete-multipart-upload"),
      createMultipartUpload: createActionInvoker(client, "file-upload/create-multipart-upload"),
      generatePresignedUrl: createActionInvoker(client, "file-upload/generate-presigned-url"),
      generatePresignedUrls: createActionInvoker(client, "file-upload/generate-presigned-urls"),
    },
    jinaReader: {
      read: createActionInvoker(client, "jina-reader/read"),
      search: createActionInvoker(client, "jina-reader/search"),
    },
    qwenDocTurbo: {
      analyze: createActionInvoker(client, "qwen-doc-turbo/analyze"),
    },
    qwenImageEditPlus: {
      edit: createActionInvoker(client, "qwen-image-edit-plus/edit"),
    },
    textToEpubIllustrate: {
      generate: createActionInvoker(client, "text-to-epub-illustrate/generate"),
    },
    tinifyPngShrink: {
      compress: createActionInvoker(client, "tinify-png-shrink/compress"),
    },
  };
}
